//
import { NextRequest, NextResponse } from 'next/server';
import { generateAllFiles } from '../../../lib/schemaGenerator';
import type { ModelNodeData } from '../../../types';
import JSZip from 'jszip';

export const runtime = 'nodejs';

export async function POST(request: NextRequest): Promise<NextResponse> {
    try {
        const body = await request.json();
        const models: ModelNodeData[] = body.models ?? [];

        if (models.length === 0) {
            return NextResponse.json({ error: 'No models provided' }, { status: 400 });
        }

        const files = generateAllFiles(models);

        // Pack into a zip — in memory
        const zip = new JSZip();
        const folder = zip.folder('generated-schemas')!;

        for (const file of files) {
            folder.file(file.filename, file.content);
        }

        // Also generate a README
        folder.file('README.md', generateReadme(models));

        const zipBuffer: any = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

        return new NextResponse(zipBuffer, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': 'attachment; filename="generated-schemas.zip"',
                'Content-Length': String(zipBuffer.length),
            },
        });
    } catch (err) {
        console.error('[generate-schema] error:', err);
        return NextResponse.json({ error: (err as Error).message }, { status: 500 });
    }
}

function generateReadme(models: ModelNodeData[]): string {
    return `# Generated Schemas
  
Auto-generated by **BackFlow** — Visual Backend Builder.

## Models (${models.length})

${models.map((m) => `- **${m.modelName}** — ${m.fields.length} fields${m.timestamps ? ' · timestamps' : ''}${m.softDelete ? ' · soft-delete' : ''}`).join('\n')}

## Files

| File | Description |
|------|-------------|
${models.flatMap((m) => [
        `| \`${m.modelName}.schema.ts\` | Mongoose schema + TypeScript interface |`,
        `| \`${m.modelName}.service.ts\` | CRUD service layer |`,
    ]).join('\n')}
| \`index.ts\` | Barrel export |

## Usage

\`\`\`typescript
import { UserService } from './generated-schemas';

// Find all active users
const users = await UserService.findAll({ active: true });

// Bulk upsert from CSV upload
await UserService.bulkUpsert(rows, 'email', 500);
\`\`\`

## Notes

- Install dependencies: \`npm install mongoose\`
- For auto-increment: \`npm install mongoose-sequence\`
- Connect mongoose before using: \`mongoose.connect(process.env.MONGODB_URI)\`
`;
}